import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import SideBar from '@/components/SideBar'
import ProviderNextAuth from '@/components/ProviderNextAuth'
import NextTopLoader from 'nextjs-toploader';


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Call Center',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="fr">
      <ProviderNextAuth>
        <body className={"flex bg-[#E4E8F3] h-screen w-screen"}>
          <NextTopLoader
          />
          <SideBar />
          <div className='flex flex-col w-full p-4 h-full justify-center items-center'>
          <div className='p-4 flex flex-col bg-base-100 justify-center items-center rounded-xl h-full w-full'>
          <div className='bg-base-200 flex flex-col rounded-lg h-full w-full'>
          {children}
          </div>

          </div>
          </div>

        </body>
      </ProviderNextAuth>
    </html>
  )
}
